//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public string UserTel { get; set; }
        public string UserUserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<byte> UserAge { get; set; }
        public Nullable<byte> UserGender { get; set; }
        public Nullable<byte> UserActive { get; set; }
    }
}
